### ISSUE TITLE
Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by egichuhis** [Nasirkhan294/personal-portfolio#9]
Hi @Nasirkhan294, good job so far on the Portfolio project. Below are some ideas and suggestions about the project, cheers! 👍🏽 

### HIGHLIGHTS 🎯 

- The project is well structured and organised into folders/directories ✅ 
- The project has a comprehensive `README` documentation ✅
- The project has been deployed properly and is accessible viewed via the `demo link` provided ✅ 
- The project is very readable and easy to maintain due to the descriptive `comments` in your files 🥇 

### RECOMMENDATIONS 🤔

- It's important to strike a balance between commenting enough to provide context and not commenting so much that the comments themselves become a burden. Good code should be self-explanatory and easy to read, with comments used sparingly and judiciously where necessary.

**Comment by Nasirkhan294** [comment]
Hi @egichuhis, Well noted your recommendation! 

Thanks for your time and consideration.
